### ISSUE TITLE
It is recommended that you develop it yourself and do not copy other people's code completely.

### ISSUE THREAD

**Issue by sudo2013** [wenguonideshou/zhuye_kim#2]
Open source project address: https://github.com/wenguonideshou/zhuye_kim
, this project is a complete copy of someone else's code, belonging to piracy resources. Can such resources be placed in GitHub? You can compare it with a legitimate website at https://www.zhuye.kim, and you'll find that the open source project's / web/templates/web/, and / web/static directory code is completely copied by someone else.

**Comment by seekdoor** [comment]
Django框架开发的    **仿**      zhuye.kim的简单个人主页/导航程序，带后台
